"""drop_quantity_amount_from_corporate_events

Revision ID: 14f9da4ed6c9
Revises: c79182a360da
Create Date: 2026-05-16 16:55:05.660681

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '14f9da4ed6c9'
down_revision = 'c79182a360da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('corporate_events', schema=None) as batch_op:
        batch_op.drop_column('amount')
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('corporate_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('amount', mysql.FLOAT(), nullable=True))

    # ### end Alembic commands ###
