"""add_transfer_to_account_id

Revision ID: 30bfabbcb919
Revises: c0da645e0828
Create Date: 2026-05-16 14:38:06.594690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30bfabbcb919'
down_revision = 'c0da645e0828'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transfer_to_account_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'accounts', ['transfer_to_account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('transfer_to_account_id')

    # ### end Alembic commands ###
