"""Initial migration

Revision ID: bd39cc8a6536
Revises: 5d77eb6e3225
Create Date: 2026-01-16 22:46:06.579812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd39cc8a6536'
down_revision = '5d77eb6e3225'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_account_stock', ['account_id', 'stock_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.drop_constraint('unique_account_stock', type_='unique')

    # ### end Alembic commands ###
