"""drop_demerger_columns_from_transactions

Revision ID: c79182a360da
Revises: 30bfabbcb919
Create Date: 2026-05-16 16:45:37.779353

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c79182a360da'
down_revision = '30bfabbcb919'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('transactions_ibfk_2'), type_='foreignkey')
        batch_op.drop_column('demerger_source_stock_id')
        batch_op.drop_column('demerger_ratio')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('demerger_ratio', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('demerger_source_stock_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('transactions_ibfk_2'), 'stocks', ['demerger_source_stock_id'], ['id'])

    # ### end Alembic commands ###
