"""add mutual funds

Revision ID: f6e5d4c3b2a1
Revises: a1b2c3d4e5f6
Create Date: 2026-09-08 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6e5d4c3b2a1'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mutual_funds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheme_code', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('amc', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('plan', sa.String(length=20), nullable=True),
    sa.Column('option', sa.String(length=20), nullable=True),
    sa.Column('isin', sa.String(length=20), nullable=True),
    sa.Column('folio', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('nav', sa.Float(), nullable=True),
    sa.Column('nav_date', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scheme_code')
    )
    op.create_table('mutual_fund_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('fund_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('nav', sa.Float(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('fees', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('transfer_to_account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['fund_id'], ['mutual_funds.id'], ),
    sa.ForeignKeyConstraint(['transfer_to_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mutual_fund_transactions_account_id'), 'mutual_fund_transactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_mutual_fund_transactions_fund_id'), 'mutual_fund_transactions', ['fund_id'], unique=False)
    op.create_index(op.f('ix_mutual_fund_transactions_transaction_date'), 'mutual_fund_transactions', ['transaction_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mutual_fund_transactions_transaction_date'), table_name='mutual_fund_transactions')
    op.drop_index(op.f('ix_mutual_fund_transactions_fund_id'), table_name='mutual_fund_transactions')
    op.drop_index(op.f('ix_mutual_fund_transactions_account_id'), table_name='mutual_fund_transactions')
    op.drop_table('mutual_fund_transactions')
    op.drop_table('mutual_funds')
    # ### end Alembic commands ###
